"use client";
import {useEffect,useState} from "react";

const platforms=["YouTube","Instagram","Facebook","TikTok","LinkedIn","X"];
const formats=["Long-form video","Shorts / Reel","Faceless explainer","Storytelling video","Educational video","News / commentary"];
const tones=["Engaging","Educational","Storytelling","Professional","Dramatic","Energetic","Cinematic"];
const stages=["research","content","creative","voice","visuals","editing","captions","seo","repurpose","quality","publish","analytics"];
const stageLabels:Record<string,string>={research:"Research",content:"Content + Hook",creative:"Creative",voice:"Voice-over",visuals:"Visuals",editing:"Editing",captions:"Captions",seo:"SEO",repurpose:"Repurpose",quality:"Quality Control",publish:"Publish",analytics:"Analytics"};

export default function Create(){
 const [topic,setTopic]=useState(""); const [audience,setAudience]=useState("General audience"); const [platform,setPlatform]=useState("YouTube"); const [format,setFormat]=useState("Long-form video"); const [tone,setTone]=useState("Engaging"); const [language,setLanguage]=useState("English"); const [duration,setDuration]=useState("8");
 const [mode,setMode]=useState("full_auto"); const [result,setResult]=useState<any>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [pipeline,setPipeline]=useState<string[]>([]); const [pipelineRunning,setPipelineRunning]=useState(false); const [plan,setPlan]=useState<any>(null); const [jobStatus,setJobStatus]=useState<any[]>([]);
 useEffect(()=>{if(!result?.projectId)return;let active=true;const poll=async()=>{try{const r=await fetch(`/api/pipeline/status?projectId=${encodeURIComponent(result.projectId)}`,{cache:"no-store"});if(r.ok&&active){const d=await r.json();setJobStatus(d.jobs||[]);}}catch{}};poll();const id=setInterval(poll,4000);return()=>{active=false;clearInterval(id)}},[result?.projectId]);
 async function start(){setLoading(true);setError("");setResult(null);setPipeline([]);setJobStatus([]);try{const [gen,orch]=await Promise.all([fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({topic,audience,platform,format,tone,language,durationMinutes:Number(duration)})}),fetch("/api/orchestrate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode})})]);const data=await gen.json();const orchestration=await orch.json();if(!gen.ok)throw new Error(data.error||"Generation failed");setResult(data);setPlan(orchestration.plan||null)}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setLoading(false)}}
 async function runPipeline(){if(!result?.projectId||!result?.contentScriptId)return;setPipelineRunning(true);setError("");for(const stage of stages){try{const r=await fetch("/api/pipeline",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:result.projectId,scriptId:result.contentScriptId,stage})});const data=await r.json();if(!r.ok)throw new Error(data.error||`${stage} failed`);setPipeline(p=>p.includes(stage)?p:[...p,stage]);}catch(e){setError(e instanceof Error?e.message:`${stage} failed`);break}}setPipelineRunning(false)}
 const completed=pipeline.length;const progress=Math.round(completed/stages.length*100);
 return <main className="container"><nav className="nav"><a href="/" className="logo" style={{textDecoration:"none"}}>VidForge AI</a><div className="nav-actions"><span className="status-dot"/> AI COMMAND CENTER <a className="nav-link" href="/production">Production</a></div></nav>
  <section className="studio-hero"><span className="badge">✦ AUTONOMOUS CONTENT ENGINE</span><h1 className="section-title">One idea. <span className="gradient-text">An entire content operation.</span></h1><p className="studio-subtitle">Research, hook-led script, packaging, voice, visuals, editing, SEO, repurposing, quality control and publishing — orchestrated from one brief.</p></section>
  <section className="workspace"><div className="workspace-head"><div><span className="eyebrow">01 · AI COMMAND BRIEF</span><h2>What are we creating?</h2></div><span className="live-pill"><span/> AI Ready</span></div><div className="topic-box"><label>Topic / idea</label><textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Example: Why most creators fail to grow on YouTube…" rows={4}/><div className="hint">VidForge turns one idea into a production-ready content package. The hook is part of the opening of the final script.</div></div><div className="control-grid"><Field label="Platform"><select value={platform} onChange={e=>setPlatform(e.target.value)}>{platforms.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Format"><select value={format} onChange={e=>setFormat(e.target.value)}>{formats.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Audience"><input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="Who is this for?"/></Field><Field label="Tone"><select value={tone} onChange={e=>setTone(e.target.value)}>{tones.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Language"><input value={language} onChange={e=>setLanguage(e.target.value)} placeholder="English / Hindi / Hinglish"/></Field><Field label="Duration"><div className="duration-wrap"><input type="number" min="1" max="30" value={duration} onChange={e=>setDuration(e.target.value)}/><span>min</span></div></Field><Field label="Automation mode"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="full_auto">Full Auto</option><option value="youtube">YouTube</option><option value="shortform">Short-form</option><option value="repurpose">Repurpose</option></select></Field></div><button className="generate-btn" onClick={start} disabled={!topic.trim()||loading}><span className="spark">✦</span>{loading?"Orchestrating AI workflow…":"Run AI Content Engine"}<span className="arrow">→</span></button>{error&&<div className="error-box">{error}</div>}</section>
  {result?.content&&<section className="result-shell"><div className="result-top"><div><span className="eyebrow">02 · INTELLIGENCE + OUTPUT</span><h2>Content command package</h2></div><span className="live-pill success"><span/> Ready for production</span></div>{plan&&<div className="pipeline-panel" style={{marginBottom:20}}><div><span className="eyebrow">AI ORCHESTRATOR</span><h2>Workflow locked</h2><p className="studio-subtitle">{plan.description}</p></div><div className="pipeline-steps">{plan.nodes?.map((x:string,i:number)=><span className="pipeline-step" key={x}>{i+1}. {x}</span>)}</div></div>}<div className="result-grid"><article className="result-card featured"><span className="mini-label">TITLE</span><h3>{result.content.title}</h3><span className="mini-label">SCRIPT OPENING / HOOK</span><p>{result.content.hook}</p></article><article className="result-card"><span className="mini-label">SEO TITLE</span><h3>{result.content.seoTitle}</h3><span className="mini-label">DESCRIPTION</span><p>{result.content.description}</p></article><article className="result-card wide"><span className="mini-label">FULL SCRIPT</span><pre>{result.content.script}</pre></article><article className="result-card"><span className="mini-label">TAGS</span><div>{(result.content.tags||[]).map((x:string,i:number)=><span className="tag" key={i}>{x}</span>)}</div></article><article className="result-card"><span className="mini-label">THUMBNAIL CONCEPTS</span><ul>{(result.content.thumbnailConcepts||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></article></div><div className="pipeline-panel"><div className="workspace-head"><div><span className="eyebrow">03 · LIVE AUTONOMOUS PRODUCTION</span><h2>Build the finished content</h2></div><strong>{progress}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:`${progress}%`}}/></div><div className="pipeline-steps">{stages.map((stage,i)=><span key={stage} className={pipeline.includes(stage)?"pipeline-step done":"pipeline-step"}>{i+1}. {stageLabels[stage]}{pipeline.includes(stage)?" ✓":""}</span>)}</div>{jobStatus.length>0&&<div className="job-monitor"><span className="mini-label">LIVE JOB MONITOR</span>{jobStatus.slice(0,8).map((j:any)=><div className="job-row" key={j.id}><span>{String(j.type).replace("PIPELINE_","")}</span><span className={`job-state ${String(j.status).toLowerCase()}`}>{j.status}</span></div>)}</div>}<button className="generate-btn" onClick={runPipeline} disabled={pipelineRunning||!result.contentScriptId||completed===stages.length}>{pipelineRunning?"Executing AI production…":completed===stages.length?"Production Complete ✓":"Execute Production Pipeline →"}</button></div></section>}
 </main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
