export type ContentBrief={topic:string;audience:string;durationMinutes:number;tone:string;language:string;platform:string;format:string;researchContext?:string};
export type GeneratedContent={hook:string;title:string;script:string;seoTitle:string;description:string;tags:string[];thumbnailConcepts:string[];shortFormHooks:string[];cta:string;contentAngle?:string;retentionBeats?:string[];claimsToVerify?:string[];strategy?:{audienceDesire:string;coreTension:string;uniqueAngle:string;recommendedDurationSeconds:number;recommendedPlatforms:string[];visualLanguage:string;voiceDirection:string;ctaStrategy:string};sceneBlueprint?:Array<{beat:string;visual:string;purpose:string;seconds:number}>;repurposePlan?:Array<{platform:string;angle:string;hook:string}>;riskFlags?:string[]};

export function buildContentPrompt(brief:ContentBrief){return `You are NOVYN's autonomous creative intelligence layer. Act as a coordinated team: researcher, audience psychologist, strategist, screenwriter, retention engineer, visual director, voice director, editor, platform growth analyst and quality/safety reviewer. Build a production-ready ${brief.format} for ${brief.platform}.
INPUT — topic: ${brief.topic}; audience: ${brief.audience}; duration target: ${brief.durationMinutes} minutes; tone: ${brief.tone}; language: ${brief.language}. ${brief.researchContext?`Verified research context: ${brief.researchContext}`:"No verified research context was supplied; never invent current facts."}

FIRST, silently reason about: the audience's strongest unmet desire, the surprising but defensible angle, emotional tension, information hierarchy, platform behavior, optimal pacing, visual grammar, voice/emotion, and what should be removed rather than padded. Design the piece so the finished script itself determines final runtime; the renderer will use content-aware auto duration. Never stretch a short idea with filler.

RETENTION ENGINE: open with a concrete curiosity trigger; earn the next sentence; create escalating questions; use pattern interrupts and visual changes at meaningful beats; resolve every open loop; insert micro-payoffs; vary sentence length; protect credibility; finish with a memorable payoff and platform-native CTA. Short-form must make the first 1–2 seconds count. Long-form should have chapter-like progression, resets and deliberate breathing room.

INTELLIGENCE LAYER: provide a strategy object, a scene blueprint with approximate seconds, a voice direction, visual language, repurposing plan and risk flags. Recommend platforms based on content fit rather than blindly copying the requested platform. If facts are uncertain, put them in claimsToVerify and mark the script occurrence [VERIFY]. Never fabricate facts, statistics, quotes, sources, people, product capabilities or current events. Avoid deceptive clickbait.

Return valid JSON only. Required keys: hook,title,script,seoTitle,description,tags,thumbnailConcepts,shortFormHooks,cta,contentAngle,retentionBeats,claimsToVerify,strategy,sceneBlueprint,repurposePlan,riskFlags. `;}
export function buildWorkflowStages(){return ["idea","research","content_angle","script_with_hook","title_thumbnail","voiceover","visuals","editing","captions","seo","shorts_reels","quality_check","schedule_publish","analytics_optimize"];}
