"use client";
import { useEffect, useState } from "react";
import "./settings.css";

type Settings = Record<string, Record<string, string | number | boolean>>;
const defaults: Settings = { appearance:{theme:"dark",density:"comfortable",motion:true},notifications:{email:true,product:true,jobs:true,marketing:false},ai:{creativity:.7,provider:"openai",model:"gpt-4o-mini"},video:{aspectRatio:"16:9",quality:"1080p Full HD",duration:60,fps:30},voice:{voice:"alloy",captions:true,captionStyle:"clean"},privacy:{analytics:true,personalization:true},accessibility:{reducedMotion:false,highContrast:false} };
const sections=[
 ["appearance","Appearance","Theme, density and motion"],["notifications","Notifications","Email and product alerts"],["ai","AI Preferences","Provider, model and creativity"],["video","Video Defaults","MP4 format, quality, duration and FPS"],["voice","Voice & Captions","Voice, captions and subtitle style"],["privacy","Privacy & Security","Analytics and personalization"],["accessibility","Accessibility","Motion, contrast and usability"]
] as const;
export default function SettingsPage(){
 const [s,setS]=useState<Settings>(defaults),[active,setActive]=useState("appearance"),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{fetch("/api/settings").then(r=>r.ok?r.json():null).then(x=>x?.settings&&setS({...defaults,...x.settings})).catch(()=>{});},[]);
 const update=(section:string,key:string,value:string|number|boolean)=>setS(x=>({...x,[section]:{...x[section],[key]:value}}));
 async function save(){setSaving(true);setSaved(false);try{const r=await fetch("/api/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({settings:s})});if(!r.ok)throw new Error();setSaved(true);}finally{setSaving(false);}}
 const a=s[active]||{};
 return <main className="settings-page"><header className="settings-top"><a href="/dashboard" className="settings-logo">NOVYN</a><div><span className="eyebrow">SYSTEM CONTROL CENTER</span><h1>Settings</h1></div><a href="/dashboard" className="back">← Dashboard</a></header><div className="settings-layout"><aside className="settings-nav"><div className="nav-caption">PREFERENCES</div>{sections.map(([id,title,desc])=><button className={active===id?"selected":""} key={id} onClick={()=>setActive(id)}><span>⚙</span><b>{title}</b><small>{desc}</small></button>)}<div className="nav-caption system-caption">SYSTEM</div><a href="/providers">Integrations →</a><a href="/pricing">Billing & Usage →</a><a href="/login">Security / Sign out →</a></aside><section className="settings-content"><div className="settings-head"><div><span className="eyebrow">{active.toUpperCase()}</span><h2>{sections.find(x=>x[0]===active)?.[1]}</h2><p>{sections.find(x=>x[0]===active)?.[2]}</p></div><span className="protected">● Protected</span></div><div className="setting-card">{active==="appearance"&&<><Row label="Theme" hint="NOVYN's optimized dark interface"><Select value={String(a.theme)} options={["dark","system","light"]} onChange={v=>update(active,"theme",v)}/></Row><Row label="Interface density" hint="Control spacing across the workspace"><Select value={String(a.density)} options={["comfortable","compact"]} onChange={v=>update(active,"density",v)}/></Row><Row label="Animations" hint="Enable polished interface motion"><Toggle value={!!a.motion} onChange={v=>update(active,"motion",v)}/></Row></>}
{active==="notifications"&&<><Row label="Email notifications" hint="Important account and product messages"><Toggle value={!!a.email} onChange={v=>update(active,"email",v)}/></Row><Row label="Job completion alerts" hint="Know when generations and renders finish"><Toggle value={!!a.jobs} onChange={v=>update(active,"jobs",v)}/></Row><Row label="Product updates" hint="Useful NOVYN feature announcements"><Toggle value={!!a.product} onChange={v=>update(active,"product",v)}/></Row><Row label="Marketing messages" hint="Optional promotional communication"><Toggle value={!!a.marketing} onChange={v=>update(active,"marketing",v)}/></Row></>}
{active==="ai"&&<><Row label="AI provider" hint="Default provider for supported workflows"><Select value={String(a.provider)} options={["openai"]} onChange={v=>update(active,"provider",v)}/></Row><Row label="Model" hint="Default text generation model"><Select value={String(a.model)} options={["gpt-4o-mini","gpt-4o"]} onChange={v=>update(active,"model",v)}/></Row><Row label="Creativity" hint="Balance consistency and creative variation"><input className="range" type="range" min="0" max="1" step=".1" value={Number(a.creativity)} onChange={e=>update(active,"creativity",Number(e.target.value))}/><output>{Number(a.creativity).toFixed(1)}</output></Row></>}
{active==="video"&&<><Row label="Output format" hint="Final renders are delivered as MP4 video"><Select value="MP4" options={["MP4"]} onChange={()=>{}}/></Row><Row label="Aspect ratio" hint="Default canvas format"><Select value={String(a.aspectRatio)} options={["16:9","9:16","1:1","4:5"]} onChange={v=>update(active,"aspectRatio",v)}/></Row><Row label="Quality" hint="HD through 4K UHD output resolution"><Select value={String(a.quality)} options={["720p HD","1080p Full HD","1440p 2K","4K UHD"]} onChange={v=>update(active,"quality",v)}/></Row><Row label="Default duration" hint="Preferred generation duration in seconds"><input className="number" type="number" min="5" max="3600" value={Number(a.duration)} onChange={e=>update(active,"duration",Number(e.target.value))}/></Row><Row label="Frame rate" hint="Default video frame rate"><Select value={String(a.fps)} options={["24","30","60"]} onChange={v=>update(active,"fps",Number(v))}/></Row></>}
{active==="voice"&&<><Row label="Voice" hint="Default AI narration voice"><Select value={String(a.voice)} options={["alloy","ash","coral","sage"]} onChange={v=>update(active,"voice",v)}/></Row><Row label="Captions" hint="Generate subtitles by default"><Toggle value={!!a.captions} onChange={v=>update(active,"captions",v)}/></Row><Row label="Caption style" hint="Default subtitle appearance"><Select value={String(a.captionStyle)} options={["clean","bold","minimal"]} onChange={v=>update(active,"captionStyle",v)}/></Row></>}
{active==="privacy"&&<><Row label="Usage analytics" hint="Help improve product performance"><Toggle value={!!a.analytics} onChange={v=>update(active,"analytics",v)}/></Row><Row label="Personalization" hint="Use preferences to tailor your workspace"><Toggle value={!!a.personalization} onChange={v=>update(active,"personalization",v)}/></Row></>}
{active==="accessibility"&&<><Row label="Reduced motion" hint="Minimize interface animation"><Toggle value={!!a.reducedMotion} onChange={v=>update(active,"reducedMotion",v)}/></Row><Row label="High contrast" hint="Increase interface contrast"><Toggle value={!!a.highContrast} onChange={v=>update(active,"highContrast",v)}/></Row></>}
</div><div className="save-bar"><span>{saved?"✓ Changes saved securely":"Changes are saved to your NOVYN account."}</span><button className="save" onClick={save} disabled={saving}>{saving?"Saving…":"Save changes"}</button></div></section></div></main>}
function Row({label,hint,children}:{label:string;hint:string;children:React.ReactNode}){return <div className="setting-row"><div><strong>{label}</strong><small>{hint}</small></div><div className="control">{children}</div></div>}
function Toggle({value,onChange}:{value:boolean;onChange:(v:boolean)=>void}){return <button aria-label="Toggle setting" className={value?"toggle on":"toggle"} onClick={()=>onChange(!value)}><span/></button>}
function Select({value,options,onChange}:{value:string;options:string[];onChange:(v:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}
